const tags = {

  tipo: {
  "bg": "BG",
  "bl": "BL",
  },

  origen: {
  "china": "China",
  "japon": "Japón",
  "korea": "Korea",
  },

  estado: {
  "finalizado": "Finalizado",
  "en-proceso": "En proceso",
  "mtl": "MTL",
  "pendiente": "Pendiente",
  },

  ambientado: {
  "apocalipsis": "Apocalipsis",
  "china-antigua": "China antigua",
  "cultivacion": "Cultivación",
  "europa-antigua": "Europa antigua",
  "fantasia": "Fantasía",
  "futurista": "Futurista",
  "moderno": "Moderno",
  "multiples-mundos": "Múltiples mundos",
  "tribal": "Tribal",
  },

  categoria: {
  "abuso": "Abuso",
  "agricultura": "Agricultura",
  "amnesia": "Amnesia",
  "animales": "Animales",
  "aristocracia": "Aristocracia",
  "bestia-humanizada": "Bestia Humanizada",
  "bestias": "Bestias",
  "canibalismo": "Canibalismo",  
  "comedia": "Comedia",
  "compromiso-roto": "Compromiso Roto",
  "cultivo": "Cultivo",
  "discapacidad": "Discapacidad",
  "drama": "Drama",
  "enemigos-a-amantes": "Enemigos a Amantes",
  "gender-bender": "Gender Bender",
  "ger": "Ger",
  "harem": "Harem",
  "hibrido": "Híbrido",
  "hombre-bestia": "Hombre Bestia",
  "incesto": "Incesto",
  "industria-del-entretenimiento": "Industria del entretenimiento",
  "inteligencia-artificial": "Inteligencia Artificial",
  "lucha-de-poder": "Lucha de poder",
  "maestro-discipulo": "Maestro-Discípulo",
  "malentendidos": "Malentendidos",
  "mascotas": "Mascotas",
  "matrimonio": "Matrimonio",
  "matrimonio-arreglado": "Matrimonio Arreglado",
  "mpreg": "Mpreg",
  "multiples-protagonistas": "Múltiples protagonistas",
  "ninos": "Niños",
  "no-humano": "No humano",
  "novela-erotica": "Novela Erótica",
  "omegaverse": "Omegaverse",
  "oneshot": "Oneshot",
  "protagonista-gong": "Protagonista Gong",
  "protagonista-op": "Protagonista OP",
  "punto-de-vista-multiple": "Punto de vista múltiple",
  "r18": "R18",
  "realeza": "Realeza",
  "redencion": "Redención",
  "reencarnacion": "Reencarnación",
  "renacimiento": "Renacimiento",
  "shota": "Shota",
  "sirena": "Sirena",
  "sistema": "Sistema",
  "sobrenatural": "Sobrenatural",
  "terror": "Terror",
  "tragedia": "Tragedia",
  "transformacion-animal": "Transformación animal",
  "transmigracion": "Transmigración",
  "transportado-a-otro-mundo": "Transportado a otro mundo",
  "venganza": "Venganza",
  "vida-diaria": "Vida Diaria",
  "vida-escolar": "Vida Escolar",
  "wuxia": "Wuxia",
  "xianxia": "Xianxia",
  "xuanhuan": "Xuanhuan",
  "yandere": "Yandere",
  "zerg": "Zerg",
  "zombies": "Zombies"
  }
};


const tagInfo = {
    ambientado: {
    "apocalipsis": "Historia ambientada en un mundo al borde del colapso o destrucción total, donde los personajes enfrentan supervivencia extrema, recursos limitados o amenazas globales.",
    "china-antigua": "Ambientación en la China histórica, con costumbres, vestimentas, política, cultura y jerarquías de la época antigua. Puede incluir emperadores, artes marciales y tradiciones milenarias.",
    "cultivacion": "Mundo donde los personajes buscan fortalecer su cuerpo, espíritu o alma a través de técnicas de cultivo. Incluye niveles de poder, energía interna y sistemas de progreso personal.",
    "europa-antigua": "Historia ambientada en épocas históricas de Europa, incluyendo culturas, reinos, sociedades medievales o antiguas, con costumbres, política y arquitectura propias de la época.",
    "fantasia": "Mundo ficticio con elementos mágicos, criaturas imaginarias, poderes sobrenaturales y leyes físicas o sociales distintas a las reales. Puede incluir magia, reinos inventados y aventuras épicas.",
    "futurista": "Ambientación en un futuro tecnológico o avanzado, con ciencia ficción, tecnología avanzada, ciudades futuristas, robótica, viajes espaciales o cambios sociales radicales.",
    "moderno": "Historia ambientada en tiempos actuales o cercanos, con elementos de la vida cotidiana moderna: tecnología, trabajo, relaciones sociales y cultura contemporánea.",
    "multiples-mundos": "Los personajes interactúan o se transportan entre distintos mundos, dimensiones o realidades paralelas, cada uno con sus propias reglas, culturas y desafíos.",
    "tribal": "Ambientación centrada en sociedades tribales o primitivas, con costumbres, ritos, jerarquías y formas de vida basadas en clanes, naturaleza y supervivencia comunitaria.",
  },
  
  categoria: {
  "abuso": "Presencia de situaciones de maltrato físico, psicológico o sexual hacia uno o más personajes. Puede formar parte del conflicto o del trasfondo de la historia.",
  "agricultura": "Historia ambientada en un contexto rural o agrícola, donde los personajes viven, trabajan o dependen del cultivo y la vida en el campo. Puede incluir granjas, pueblos, cosechas y tradiciones campesinas.",
  "amnesia": "Uno de los protagonistas pierde parcial o totalmente su memoria, afectando su identidad, relaciones y decisiones. El conflicto emocional surge al intentar recuperar recuerdos, entender su pasado o reconectarse con otros personajes.",
  "animales": "El protagonista es un animal y vive principalmente como tal. La historia se centra en su vida, instintos, supervivencia o interacción con otros animales, aunque puede tener inteligencia humana (por reencarnación u otros medios).",
  "aristocracia": "Personajes pertenecientes a familias nobles o de alto estatus social, sin ser necesariamente realeza. Incluye nobles, duques, condes o terratenientes influyentes, con vida marcada por privilegios, obligaciones y jerarquías sociales.",
  "bestia-humanizada": "Criaturas no humanas con características sobrenaturales, incluyendo animales, plantas espirituales u otras formas de vida que desarrollan conciencia y habilidades a través del cultivo u otros medios.",
  "bestias": "Criaturas no humanas con características sobrenaturales, como bestias mágicas, demoníacas o cultivadoras. Suelen poseer habilidades especiales, inteligencia elevada o sistemas de poder, pero mantienen una forma no humana.",
  "canibalismo": "Presencia de consumo de carne humana dentro de la historia. Puede formar parte de la supervivencia, el conflicto o dinámicas entre personajes, y no necesariamente se presenta de forma gráfica o explícita.",
  "comedia": "Historias centradas en el humor, situaciones absurdas o divertidas que generan risa o entretenimiento.",
  "compromiso-roto": "Uno de los personajes tenía un compromiso matrimonial previsto, ya sea romántico o por acuerdo familiar, y este compromiso es interrumpido o cancelado por algún motivo. La historia explora las consecuencias emocionales, los conflictos que surgen y cómo los personajes reaccionan ante la ruptura del acuerdo.",
  "cultivo": "Personaje utiliza el cultivo como método de mejora o evolución, independientemente de la ambientación del mundo. Puede incluir niveles de poder, energía interna, técnicas especiales o prácticas que incrementen su fuerza, habilidades o longevidad.",
  "discapacidad": "Indica que uno de los protagonistas o personajes importantes tiene alguna discapacidad física o sensorial, que influye en su vida cotidiana o en sus interacciones con otros personajes.",
  "drama": "Historia centrada en conflictos emocionales profundos, dilemas personales y relaciones interpersonales complejas. Se enfoca en el desarrollo psicológico y las tensiones de los personajes.",
  "enemigos-a-amantes": "La relación comienza con conflictos, rivalidades o antagonismo, y evoluciona hacia romance o afecto. El drama y los malentendidos son comunes en este tipo de dinámica.",
  "gender-bender": "Obra en la que un protagonista asume temporalmente el rol de otro género, ya sea por vestimenta, identidad o estrategia.",
  "ger": "Personaje perteneciente a un tercer género dentro del universo narrativo, distinto de hombre y mujer, con características biológicas o sociales propias. En muchas historias este género puede incluir rasgos únicos y tiene la capacidad de quedar embarazado, forma parte de la construcción de un mundo con reglas biológicas propias del género de la obra.",
  "harem": "Un protagonista mantiene relaciones románticas o sexuales con múltiples personas, quienes generalmente sienten atracción por él/ella. Las relaciones pueden ser explícitas o implícitas.",
  "hibrido": "Personaje cuya naturaleza combina múltiples razas, especies o linajes, coexistiendo dentro de su identidad. Puede manifestar diferentes formas o habilidades según su herencia, sin pertenecer completamente a una sola especie.",
  "hombre-bestia": "Personaje perteneciente a una raza humanoide con rasgos animales como parte natural de su especie. Estas características son permanentes y forman parte de la sociedad del mundo.",
  "incesto": "Relaciones románticas o sexuales entre familiares directos o cercanos. Se utiliza en el contexto de la narrativa y no necesariamente con connotación moral, sino como dinamismo dramático o romántico.",
  "industria-del-entretenimiento": "Historia centrada en la vida profesional y personal de personajes que trabajan en el mundo del entretenimiento, como cantantes, actores, idols o artistas. Las tramas suelen girar en torno a presentaciones, competencias, giras, fama, relaciones laborales y personales dentro de este entorno.",
  "inteligencia-artificial": "Personaje que no es humano sino una IA o entidad digital que desarrolla conciencia, emociones o identidad propia.",
  "lucha-de-poder": "La historia se centra en la competencia por control, autoridad o dominio dentro de un grupo, sociedad, reino o institución. Puede incluir intrigas, estrategias, enfrentamientos y dinámicas jerárquicas.",
  "maestro-discipulo": "Relación donde uno de los protagonistas actúa como mentor o guía del otro. Puede incluir entrenamiento, enseñanza de habilidades, artes marciales, cultivo, o crecimiento personal, con un vínculo afectivo o romántico que se desarrolla a lo largo de la historia.",
  "malentendidos": "Conflictos causados por errores de comunicación, suposiciones o percepciones equivocadas entre los personajes. Genera drama, comedia o romance, dependiendo del tono de la historia.",
  "mascotas": "Se utiliza cuando uno de los protagonistas comienza su historia o pasa parte de ella como mascota o animal de compañía, ya sea porque transmigra, renace en un animal, alterna entre cuerpo animal y humano, o es cuidado por otra persona. Esta etiqueta no se refiere a mascotas secundarias de apoyo, sino a protagonistas cuya identidad y arco narrativo incluyen la condición de mascota.",
  "matrimonio": "Historia donde los protagonistas llegan a casarse en algún punto de la trama, ya sea por decisión mutua, por amor o circunstancias externas.",
  "matrimonio-arreglado": "La unión matrimonial se realiza por decisión externa (familia, política, acuerdos), no por amor inicial. La historia suele explorar cómo evolucionan los sentimientos entre los protagonistas dentro de ese contexto.",
  "mpreg": "Protagonista masculino queda embarazado o tiene capacidad reproductiva, ya sea por medios sobrenaturales, ciencia ficción, magia o biología alternativa.",
  "multiples-protagonistas": "Historia contada desde varios personajes principales, donde cada uno tiene un arco propio y contribuye de manera significativa al desarrollo de la trama.",
  "ninos": "Personajes menores de edad que afectan la historia de forma significativa, ya sea por relaciones familiares, conflictos, desarrollo de los protagonistas o tramas secundarias.",
  "no-humano": "El protagonista no pertenece a la raza humana. Puede incluir animales, bestias, razas híbridas, criaturas míticas o seres alienígenas, sin importar su forma o nivel de inteligencia.",
  "novela-erotica": "Obra en la que el contenido sexual o las escenas íntimas son centrales en la narrativa. La historia se centra en relaciones sexuales y dinámicas eróticas, en la que el contenido sexual o las escenas íntimas son el enfoque principal de la narrativa.",
  "omegaverse": "Sistema social basado en jerarquías de características biológicas: Alfa, Beta, Omega. Incluye dinámicas de atracción, instinto, marcaje y relaciones afectivas específicas.",
  "oneshot": "Historia completa en un solo capítulo o entrega. No forma parte de una serie más larga y suele tener cierre definitivo de la trama.",
  "protagonista-gong": "La historia sigue principalmente al Gong (top), quien tiene el arco central, sus metas y desarrollo personal. Aunque otros personajes, como el Shou (bottom), tengan importancia, el enfoque principal está en las decisiones, misiones y crecimiento del Gong.",
  "protagonista-op": "Protagonista que posee habilidades, poderes o ventajas extremadamente superiores desde el inicio o muy rápido en la historia. Su capacidad sobresale de forma notable sobre los demás personajes, lo que puede influir en la dinámica de la trama.",
  "punto-de-vista-multiple": "La narrativa se alterna entre los puntos de vista de distintos personajes, mostrando sus pensamientos, sentimientos y experiencias. Puede incluir protagonistas y secundarios importantes, permitiendo al lector comprender distintos ángulos de la historia.",
  "r18": "La obra contiene escenas sexuales o de contenido adulto, pero estas no dominan la historia. Son partes complementarias que aparecen en momentos puntuales. La trama principal puede centrarse en romance, aventura, drama, etc., y el contenido explícito no es el eje central.",
  "realeza": "Personajes que pertenecen a la familia real (emperadores, reyes, príncipes, princesas). La historia puede incluir protocolos, intrigas palaciegas y responsabilidades propias de su estatus.",
  "redencion": "Historia donde un personaje intenta enmendar acciones pasadas y cambiar su destino o su forma de ser.",
  "reencarnacion": "El protagonista muere y nace nuevamente en otro cuerpo, ya sea en el mismo mundo o en uno diferente. Conserva total o parcialmente sus recuerdos de su vida anterior, lo que influye en sus decisiones y desarrollo.",
  "renacimiento": "El protagonista muere o revive y regresa a un punto anterior de su propia vida, generalmente en el mismo cuerpo y mundo. Conserva sus recuerdos, lo que le permite cambiar decisiones pasadas y alterar su destino.",
  "shota": "Personaje masculino joven (niño o adolescente) que juega un rol central en la historia, ya sea protagonista o parte del romance. La etiqueta describe edad y rol, no la moralidad de la historia. Puede formar parte de dinámicas sensibles.",
  "sirena": "Ser no humano con forma híbrida, generalmente mitad humano y mitad criatura acuática. Incluye variantes similares como tritones u otras razas marinas inteligentes.",
  "sistema": "Herramienta tipo interfaz o mecanismo estructurado que otorga misiones, habilidades, recompensas o niveles de progresión al protagonista.",
  "sobrenatural": "Presencia de fenómenos o entidades que no pueden explicarse por leyes naturales, como espíritus, eventos paranormales o poderes inexplicables.",
  "terror": "Historia diseñada para provocar miedo, ansiedad o tensión, con elementos oscuros, amenazas, monstruos o situaciones que ponen en riesgo la seguridad o cordura de los personajes.",
  "tragedia": "Historia donde los eventos conducen a desenlaces desafortunados o dolorosos para los personajes. El sufrimiento, la pérdida y la fatalidad son elementos centrales.",
  "transformacion-animal": "Personaje que experimenta un cambio físico hacia un animal o adquiere rasgos animales de forma temporal o permanente. Esto puede ser voluntario o forzado por magia, sistema, técnica, etc.",
  "transmigracion": "El protagonista es trasladado a otro cuerpo o identidad, manteniendo su conciencia original. A diferencia de la reencarnación, no comienza desde el nacimiento, sino que ocupa directamente otro cuerpo o identidad.",
  "transportado-a-otro-mundo": "El protagonista es llevado a otro mundo con su propio cuerpo, sin cambiar de identidad. Debe adaptarse a un entorno completamente nuevo conservando su apariencia.",
  "venganza": "La historia gira en torno a un personaje que busca justicia, retribución o venganza por un daño, traición o injusticia recibida. Este conflicto impulsa la trama y puede combinarse con romance o drama.",
  "vida-diaria": "Historias centradas en la vida cotidiana, mostrando situaciones comunes, rutinas o relaciones de los personajes sin elementos extraordinarios.",
  "vida-escolar": "Historia centrada en la vida escolar o universitaria de los personajes, mostrando interacciones entre compañeros, actividades académicas, amistades, romances y conflictos típicos del entorno educativo.",
  "wuxia": "Historia centrada en artes marciales tradicionales, honor, clanes, combates físicos y códigos de conducta propios de la antigua China. (Humanos normales o casi humanos, artes marciales, sin magia ni cultivo)",
  "xianxia": "Fantasía basada en el cultivo y el desarrollo espiritual, donde los personajes buscan la inmortalidad y poseen poderes sobrenaturales. (Cultivo y poderes sobrenaturales estrictos, búsqueda de inmortalidad)",
  "xuanhuan": "Fantasía que combina elementos de cultivo con sistemas de poder o magia más libres y de reglas flexibles, sin seguir estrictamente las normas del xianxia. (Mezcla libre de cultivo, magia, sistemas, tecnología; reglas flexibles)",
  "yandere": "Uno de los protagonistas tiene afecto obsesivo, celos extremos o comportamiento posesivo hacia otro personaje. Puede incluir violencia, manipulación o conductas extremas para proteger o asegurar la relación.",
  "zerg": "Especie extraterrestre humanoide con rasgos insectoides, cuya biología y roles de género funcionan de forma distinta a los humanos, incluyendo dinámicas reproductivas y sociales propias.",
  "zombies": "Presencia de zombies en la historia, ya sea como amenaza, parte del entorno o como condición de algunos personajes, incluyendo protagonistas."
  }
};
