const tags = {

  tipo: {
  "rofan": "Rofan",
  "danmei": "Danmei",
  },

  estado: {
  "finalizado": "Finalizado",
  "en-proceso": "En proceso",
  "mtl": "MTL",
  "pendiente": "Pendiente",
  },

  ambientado: {
  "apocalipsis": "Apocalipsis",
  "china-antigua": "China antigua",
  "cultivacion": "Cultivación",
  "europa-antigua": "Europa antigua",
  "fantasia": "Fantasía",
  "futurista": "Futurista",
  "moderno": "Moderno",
  "multiples-mundos": "Múltiples mundos",
  "tribal": "Tribal",
  },

  categoria: {
  "agricultura": "Agricultura",
  "amnesia": "Amnesia",
  "animales": "Animales",
  "aristocracia": "Aristocracia",
  "bestias": "Bestias",
  "bestia-humanizada": "Bestia Humanizada",
  "comedia": "Comedia",
  "compromiso-roto": "Compromiso Roto",
  "cultivo": "Cultivo",
  "discapacidad": "Discapacidad",
  "drama": "Drama",
  "enemigos-a-amantes": "Enemigos a Amantes",
  "espectaculo": "Espectáculo",
  "gender-bender": "Gender Bender",
  "ger": "Ger",
  "harem": "Harem",
  "hombre-bestia": "Hombre Bestia",
  "incesto": "Incesto",
  "inteligencia-artificial": "Inteligencia Artificial",
  "lucha-de-poder": "Lucha de poder",
  "maestro-discipulo": "Maestro-Discípulo",
  "malentendidos": "Malentendidos",
  "mascotas": "Mascotas",
  "matrimonio": "Matrimonio",
  "matrimonio-arreglado": "Matrimonio Arreglado",
  "mpreg": "Mpreg",
  "multiples-protagonistas": "Múltiples protagonistas",
  "ninos": "Niños",
  "no-humano": "No humano",
  "omegaverse": "Omegaverse",
  "oneshot": "Oneshot",
  "protagonista-gong": "Protagonista Gong",
  "protagonista-op": "Protagonista OP",
  "punto-de-vista-multiple": "Punto de vista múltiple",
  "r18": "R18",
  "realeza": "Realeza",
  "reencarnacion": "Reencarnación",
  "renacimiento": "Renacimiento",
  "school-life": "School Life",
  "shota": "Shota",
  "sirena": "Sirena",
  "sistema": "Sistema",
  "slice-of-life": "Slice of life",
  "smut": "Smut",
  "sobrenatural": "Sobrenatural",
  "terror": "Terror",
  "tragedia": "Tragedia",
  "transformacion-animal": "Transformación animal",
  "transmigracion": "Transmigración",
  "transportado-a-otro-mundo": "Transportado a otro mundo",
  "venganza": "Venganza",
  "wuxia": "Wuxia",
  "xianxia": "Xianxia",
  "xuanhuan": "Xuanhuan",
  "yandere": "Yandere",
  "zerg": "Zerg",
  "zombies": "Zombies"
  }
};
